timeout = 5
persistent = false
show_track_cover = true
depth = 3
app_name = 'C* Music Player'
summary = '{title}'
body = '<b>album:</b> {album}<br/><b>Artist:</b> {artist} - {date}'
cmus_remote_bin_path = 'cmus-remote'
interval = 1000
link = false
force_use_external_cover = false
force_use_external_lyrics = false
no_use_external_cover = false
no_use_external_lyrics = false
show_player_notifications = false
volume_notification_body = 'Volume changed to {volume}%'
volume_notification_summary = '{title}'
volume_notification_timeout = 1
shuffle_notification_body = 'Shuffle mode changed to {shuffle}'
shuffle_notification_summary = '{title}'
shuffle_notification_timeout = 1
repeat_notification_body = 'Repeat mode changed to {repeat}'
repeat_notification_summary = '{title}'
repeat_notification_timeout = 1
aaa_mode_notification_body = 'AAA mode changed to {aaa_mode}'
aaa_mode_notification_summary = '{title}'
aaa_mode_notification_timeout = 1
lyrics_notification_body = '{lyrics}'
lyrics_notification_summary = 'Lyrics'
status_notification_body = '<b>{status}</b>'
status_notification_summary = '{title}'
status_notification_timeout = 1
